### ISSUE TITLE
 File `dtklogos.sty' not found.

### ISSUE THREAD

**Issue by brokenprogrammer** [linuxprofessor/Exjobbsmall-LNU#5]
Det verkar som att packetet dtk har uppdaterat filnamnet för "dtklogos.sty" till "dtk-logos.sty".
Jag löste detta problemet i mallen jag laddade ner genom att byta kodrad 21 i **_exjobbsmall_lnu.tex_**
från
`\usepackage{dtklogos} % Logos för t.ex. LaTeX, BibTeX, etc.`
till 
`\usepackage{dtk-logos} % Logos för t.ex. LaTeX, BibTeX, etc.`

Om du hade kunnat ge grönt ljus så hade jag gärna ändrat detta med en snabb pull request.

Här kan du se ändringen i CTAN: [https://www.ctan.org/tex-archive/usergrps/dante/dtk](https://www.ctan.org/tex-archive/usergrps/dante/dtk)
Här är själva filen dtk-logos.sty: [http://ftp.acc.umu.se/mirror/CTAN/usergrps/dante/dtk/dtk-logos.sty](http://ftp.acc.umu.se/mirror/CTAN/usergrps/dante/dtk/dtk-logos.sty)

**Comment by linuxprofessor** [comment]
Fixat till detta (äntligen)
